services:
  db:
    image: postgres:latest
    command:
      - -c
      - config_file=/etc/postgresconf/my-postgres.conf
      - -c
      - hba_file=/etc/postgresconf_hba/pg_hba.conf
    restart: always
    environment:
      DB_USER: /run/secrets/db_user
      DB_PASSWORD: /run/secrets/db_password
      DB_DATABASE:  /run/secrets/db_database
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    ports:
      - '127.0.0.1:5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./conf/:/etc/postgresconf/
      - ./hba/:/etc/postgresconf_hba/
      - ./init/:/docker-entrypoint-initdb.d/
    secrets:
      - postgres_user
      - postgres_password
      - db_user
      - db_password
      - db_database
volumes:
  db:
    driver: local

secrets:
  postgres_user:
    file: ./postgres_user.secret
  postgres_password:
    file: ./postgres_password.secret
  db_user:
    file: ./db_user.secret
  db_password:
    file: ./db_password.secret
  db_database:
    file: ./db_database.secret